# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/alecthomas/participle
%global goipath         github.com/alecthomas/participle/v2
Version:                2.1.1

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
A parser library for Go.}

%global golicenses      COPYING
%global godocs          _examples CHANGES.md README.md TUTORIAL.md\\\
                        bin/README.hermit.md

Name:           %{goname}
Release:        %autorelease
Summary:        A parser library for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYING
%doc _examples CHANGES.md README.md TUTORIAL.md bin/README.hermit.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
