[package]
name = "ff2mpv-rust"
version = "1.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.93", features = ["preserve_order"] }

[profile.release-full]
inherits = "release"
strip = "symbols"
lto = "fat"
