# Generated by go2rpm 1.9.0
%bcond_without check

# https://git.sr.ht/~whynothugo/autovdirsyncer
%global goname autovdirsyncer
%global goipath         git.sr.ht/~whynothugo/autovdirsyncer
%global forgeurl        https://git.sr.ht/~whynothugo/autovdirsyncer
Version:                v0.2.1
%global tag             v0.2.1

%gometa -f


%global common_description %{expand:
Autovdirsyncer is a wrapper to daemonise vdirsyncer.
}

%global golicenses      LICENCE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Execute scripts on IMAP mailbox changes (new/deleted/updated messages) using IDLE, golang version

License:        GPL-3.0-only
URL:            %{gourl}
Source0:        %{gosource}
Source1:        %{forgeurl}/tree/%{version}/item/%{goname}.service

BuildRequires: systemd-rpm-macros
BuildRequires: systemd-devel
BuildRequires: systemd
%{?systemd_requires}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/%{goname} %{goipath}

%install
install -dm 0755 -v %{buildroot}/%{_userunitdir}/
install -Dm 0644 -v -t %{buildroot}/%{_userunitdir}/ %{goname}.service

%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENCE
%doc README.md
%{_bindir}/*
%{_userunitdir}/%{goname}.service

%gopkgfiles

%changelog
%autochangelog
