#! /bin/sh

set -ex

VERSION="0.1.0"

git config --global user.name "John Doe"
git config --global user.email johndoe@example.com

git clone https://git.sr.ht/~whynothugo/systemd-autoreload
(
    cd systemd-autoreload
    git archive --format=tar.gz -o ../systemd-autoreload-${VERSION}.tar.gz --prefix systemd-autoreload-${VERSION}/ main
)

rust2rpm -V ./systemd-autoreload
curl https://raw.githubusercontent.com/cyrinux/cyrinux-copr/main/rust-systemd-autoreload/spec.diff -o
git apply spec.diff

cat systemd-autoreload.spec
