[package]
name = "wormhole-rs"
version = "0.6.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.120", features = ["rc"] }
serde_json = "1.0.61"
serde_derive = "1.0.120"
log = "0.4.13"
url = { version = "2.2.2", features = ["serde"] }
futures = "0.3.12"
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }

# CLI specific dependencies
magic-wormhole = { path = "..", features = ["all"], version = "0.6.1" }
clap = { version = "3.1.5", features = ["cargo", "derive", "wrap_help"] }
clap_complete = "3.1.4"
env_logger = "0.10.0"
console = "0.15.0"
indicatif = "0.17.0"
dialoguer = "0.10.0"
color-eyre = "0.6.0"
number_prefix = "0.4.0"
ctrlc = "3.2.1"
cli-clipboard = "0.4.0"
qr2term = "0.3.0"
