# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/elliotchance/orderedmap
%global goipath         github.com/elliotchance/orderedmap
Version:                1.5.1

%gometa -f


%global common_description %{expand:
🔃 An ordered map in Go with amortized O(1) for Set, Get, Delete and Len.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        🔃 An ordered map in Go with amortized O(1) for Set, Get, Delete and Len

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
