# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/mikefarah/yq
%global goipath         github.com/mikefarah/yq
Version:                4.40.5

%gometa -f

%global goname yq

%global common_description %{expand:
Yq is a portable command-line YAML, JSON, XML, CSV, TOML  and properties
processor.}

%global golicenses      LICENSE
%global godocs          examples CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        how-it-works.md project-words.txt\\\
                        release_instructions.txt release_notes.txt\\\
                        debian/changelog doc

Name:           %{goname}
Release:        %autorelease
Summary:        Yq is a portable command-line YAML, JSON, XML, CSV, TOML  and properties processor

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%gobuild -o %{gobuilddir}/bin/yq %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc examples CODE_OF_CONDUCT.md CONTRIBUTING.md README.md how-it-works.md
%doc project-words.txt release_instructions.txt release_notes.txt
%doc debian/changelog doc
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
