# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
%global __cargo_is_lib() 0

%global crate push2talk

Name:           rust-push2talk
Version:        1.2.5
Release:        %autorelease
Summary:        Push to talk application is working with both wayland/x11 and pulseaudio

License:        ISC
URL:            https://crates.io/crates/push2talk
Source:         %{crates_source}
Source:         https://levis.name/packaging/push2talk-1.2.5-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25

%global _description %{expand:
This Push to talk application is working with both wayland/x11 and
pulseaudio (pipewire).}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/push2talk

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
