# Generated by rust2rpm 25
%bcond_without check 0

%global crate push2talk

Name:           rust-push2talk
Version:        1.2.7
Release:        2
Summary:        Push to talk application is working with both wayland/x11 and pulseaudio

License:        ISC
URL:            https://crates.io/crates/push2talk
Source0:        %{crates_source}
Source1:        https://raw.githubusercontent.com/cyrinux/push2talk/%{version}/push2talk.service

BuildRequires:  cargo-rpm-macros >= 25
BuildRequires:  rust-libudev-devel
BuildRequires:  rust-libpulse-binding-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  libinput-devel
Requires:       pipewire-pulseaudio

%global _description %{expand:
This Push to talk application is working with both wayland/x11 and
pulseaudio (pipewire).}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        ISC

%description -n %{crate} %{_description}

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
%{__install} -Dm 0644 -t %{buildroot}%{_userunitdir}/ push2talk.service

%if %{with check}
%check
%cargo_test
%endif

%files       -n %{crate}
%license LICENSE.md
%license LICENSE.dependencies
%doc README.md
%{_userunitdir}/push2talk.service
%{_bindir}/push2talk

%changelog
%autochangelog
