#! /bin/sh

set -ex

export COPR_PACKAGE

git config --global user.name "Cyril Levis"
git config --global user.email copr@levis.name

CRATE="${COPR_PACKAGE#rust-}"

# Create vendor and spec
rust2rpm -V -s -a "${CRATE}"

# Patch spec file
curl "https://raw.githubusercontent.com/cyrinux/cyrinux-copr/main/${COPR_PACKAGE}/${COPR_PACKAGE}.spec.diff" | git apply -v
