# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/esiqveland/notify
%global goipath         github.com/esiqveland/notify
Version:                0.11.2

%gometa -f


%global common_description %{expand:
Notify is a go dbus implementation for delivering desktop notifications over
dbus.}

%global golicenses      LICENSE.txt
%global godocs          example README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Notify is a go dbus implementation for delivering desktop notifications over dbus

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Dec 25 2023 Cyril Levis <git@levis.name> 0.11.2-1
- new package built with tito

%autochangelog
