# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/jinzhu/copier
%global goipath         github.com/jinzhu/copier
Version:                0.4.0

%gometa -f


%global common_description %{expand:
Copier for golang, copy value from struct to struct and more.}

%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Copier for golang, copy value from struct to struct and more

License:        # FIXME
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
