# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/saljam/webwormhole
%global forgeurl        https://github.com/saljam/webwormhole
%global goipath         github.com/saljam/webwormhole
%global commit          6ceee76274ee881e828bd48c5cc15c758b9ad77c

%gometa -f

%global goname webwormhole

%global common_description %{expand:
Peer authenticated WebRTC.}

%global golicenses      LICENSE
%global godocs          README

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Peer authenticated WebRTC

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall

install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
