Name:           cyrinux-metapackage
Version:        1
Release:        %autorelease
Summary:        Cyrinux Metapackage for asahi
License: MIT

%description

BuildRequires: NetworkManager-openvpn
BuildRequires: NetworkManager-openvpn-gnome
BuildRequires: NetworkManager-wifi
BuildRequires: ShellCheck
BuildRequires: SwayNotificationCenter
BuildRequires: abattis-cantarell-fonts
BuildRequires: acpi
BuildRequires: adwaita-qt5
BuildRequires: adwaita-qt6
BuildRequires: alsa-ucm-asahi
BuildRequires: asahi-fwupdate
BuildRequires: asahi-platform-metapackage
BuildRequires: asahi-repos
BuildRequires: asdf-vm
BuildRequires: basesystem
BuildRequires: bat
BuildRequires: binwalk
BuildRequires: browserpass
BuildRequires: browserpass-chromium
BuildRequires: browserpass-firefox
BuildRequires: calibre
BuildRequires: cargo
BuildRequires: chromium
BuildRequires: containerd.io
BuildRequires: copr-cli
BuildRequires: darkman
BuildRequires: dash
BuildRequires: dejavu-fonts-all
BuildRequires: direnv
BuildRequires: dnf
BuildRequires: docker-buildx-plugin
BuildRequires: docker-ce
BuildRequires: docker-ce-cli
BuildRequires: docker-compose-plugin
BuildRequires: dracut-asahi
BuildRequires: dracut-kbd-backlight
BuildRequires: dua-cli
BuildRequires: earlyoom
BuildRequires: eza
BuildRequires: fd-find
BuildRequires: fedora-asahi-remix-scripts
BuildRequires: filesystem
BuildRequires: firefox
BuildRequires: flatpak
BuildRequires: fontawesome-fonts-all
BuildRequires: fping
BuildRequires: freerdp
BuildRequires: fzf
BuildRequires: gdisk
BuildRequires: geoclue2-demos
BuildRequires: gh
BuildRequires: ghq
BuildRequires: gimp
BuildRequires: git-delta
BuildRequires: gitui
BuildRequires: glibc-all-langpacks
BuildRequires: gnome-keyring
BuildRequires: go2rpm
BuildRequires: gocryptfs
BuildRequires: goimapnotify
BuildRequires: golang
BuildRequires: google-noto-sans-fonts
BuildRequires: google-noto-serif-fonts
BuildRequires: graphviz
BuildRequires: grub2-efi-aa64
BuildRequires: grub2-efi-aa64-modules
BuildRequires: grubby
BuildRequires: helvum
BuildRequires: htop
BuildRequires: hyprland
BuildRequires: hyprland-autoname-workspaces
BuildRequires: initial-setup
BuildRequires: inotify-tools
BuildRequires: isync
BuildRequires: iwd
BuildRequires: kak-lsp
BuildRequires: kakoune
BuildRequires: kernel-16k
BuildRequires: kernel-16k-modules-extra
BuildRequires: lato-fonts
BuildRequires: lftp
BuildRequires: liberation-fonts
BuildRequires: libgnome-keyring
BuildRequires: light
BuildRequires: meld
BuildRequires: mock
BuildRequires: mpv
BuildRequires: neomutt
BuildRequires: network-manager-applet
BuildRequires: nextcloud-client
BuildRequires: nmap
BuildRequires: nmtrust
BuildRequires: notmuch
BuildRequires: obs-studio
BuildRequires: open-sans-fonts
BuildRequires: pam-u2f
BuildRequires: pamu2fcfg
BuildRequires: paperwork
BuildRequires: pass
BuildRequires: passmenu
BuildRequires: pavucontrol
BuildRequires: perl
BuildRequires: pinentry-qt
BuildRequires: pipewire-utils
BuildRequires: polkit-gnome
BuildRequires: privoxy
BuildRequires: pulseaudio-utils
BuildRequires: pwgen
BuildRequires: pyp2rpm
BuildRequires: python-unversioned-command
BuildRequires: qalculate-gtk
BuildRequires: qemu
BuildRequires: restic
BuildRequires: rust-analyzer
BuildRequires: rust2rpm
BuildRequires: rustfmt
BuildRequires: setroubleshoot
BuildRequires: shim-aa64
BuildRequires: signal-desktop
BuildRequires: songrec
BuildRequires: sqlite
BuildRequires: supertuxkart
BuildRequires: swappy
BuildRequires: swaybg
BuildRequires: swayidle
BuildRequires: swaylock
BuildRequires: systembus-notify
BuildRequires: systemd-oomd-defaults
BuildRequires: tarsnap
BuildRequires: terminus-fonts-console
BuildRequires: tig
BuildRequires: tiny-dfr
BuildRequires: tito
BuildRequires: tlp
BuildRequires: tor
BuildRequires: trash-cli
BuildRequires: typetogether-literata-fonts
BuildRequires: uboot-images-armv8
BuildRequires: udiskie
BuildRequires: update-m1n1
BuildRequires: usbguard-dbus
BuildRequires: vdirsyncer
BuildRequires: vimiv-qt
BuildRequires: waybar
BuildRequires: wev
BuildRequires: wireguard-tools
BuildRequires: wldash
BuildRequires: yubikey-touch-detector
BuildRequires: zathura-pdf-mupdf
BuildRequires: zsh


%changelog
%autochangelog
