# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
%global __cargo_is_lib() 0

%global debug_packageAA %{nil}

%global crate magic-wormhole

Name:           rust-magic-wormhole
Version:        0.6.1
Release:        %autorelease
Summary:        Get things from one computer to another, safely

License:        EUPL-1.2
URL:            https://crates.io/crates/magic-wormhole
Source0:        https://github.com/magic-wormhole/magic-wormhole.rs/archive/refs/tags/0.6.1.tar.gz

BuildRequires:  cargo-rpm-macros >= 25

%global _description %{expand:
Get things from one computer to another, safely.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        EUPL-1.2

%description -n %{crate} %{_description}

%prep
tar xzf %{version}.tar.gz --strip-components=1 magic-wormhole.rs-%{version}/cli/
sed -i 's/path = "\.\."/version = "*"/g' cli/Cargo.toml
mv cli %{crate}-%{version}
%cargo_prep

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%files  -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/magic-wormhole

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif


%changelog
%autochangelog
