# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/alecthomas/participle
%global goipath         github.com/alecthomas/participle
Version:                2.1.1

%gometa -f


%global common_description %{expand:
A parser library for Go.}

%global golicenses      COPYING
%global godocs          _examples CHANGES.md README.md TUTORIAL.md\\\
                        bin/README.hermit.md

Name:           %{goname}
Release:        %autorelease
Summary:        A parser library for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYING
%doc _examples CHANGES.md README.md TUTORIAL.md bin/README.hermit.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
