# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/browserpass/browserpass-native
%global goipath         github.com/browserpass/browserpass-native
Version:                3.1.0
%global tag             3.1.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global goname browserpass-native

%global common_description %{expand:
Browserpass native client app.}

%global golicenses      LICENSE
%global godocs          PROTOCOL.md README.md debug/README.md debug/request-\\\
                        configure.hex.txt

Name:           %{goname}
Release:        %autorelease
Summary:        Browserpass native client app

License:        ISC
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/browserpass-native %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc PROTOCOL.md README.md debug/README.md debug/request-configure.hex.txt
%{_bindir}/*

%gopkgfiles

%changelog
* Mon Dec 25 2023 Cyril Levis <git@levis.name> 3.1.0-1
- new package built with tito

%autochangelog
