# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/fatih/set
%global goipath         github.com/fatih/set
Version:                0.2.1

%gometa -f


%global common_description %{expand:
Set data structure for Go.}

%global golicenses      LICENSE.md
%global godocs          examples README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Set data structure for Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Dec 25 2023 Cyril Levis <git@levis.name> 0.2.1-1
- new package built with tito

%autochangelog
