# Generated by rust2rpm 25
%bcond_without check

# prevent library files from being installed
%global __cargo_is_lib() 0

%global crate dfrs

Name:           rust-dfrs
Version:        0.0.7
Release:        %autorelease
Summary:        Display file system space usage using graphs and colors

License:        MIT
URL:            https://crates.io/crates/dfrs
Source:         %{crates_source}
Source:         dfrs-0.0.7-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 25

%global _description %{expand:
Display file system space usage using graphs and colors.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/dfrs

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
